<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Chat.aspx.cs" Inherits="Fastagram.Chat" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <script src="Scripts/jquery-3.3.1.min.js" ></script>
    <!--Reference the SignalR library. -->
    <script src="Scripts/jquery.signalR-2.4.1.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="signalr/hubs"></script>
</head>
<body>
    <input type="text" id="message" />
    <div id="room"></div>
    <input type="button" id="sendmessage" value="Send" />
    <script type="text/javascript">
        $(function () {
            var chat = $.connection.notifyHub;

            chat.client.hello = (message) => {
                var msg = $('<div />').text(message).html();
                $('#room').append(message);
            }

            $.connection.hub.start().done(() => {
                $('#sendmessage').click(() => {
                    // Call the Send method on the hub. 
                    chat.server.hello($('#message').val());
                    // Clear text box and reset focus for next comment. 
                    $('#message').val('').focus();
                });
            })
        });
    </script>
    <form id="form1" runat="server">
        <div>
        </div>
    </form>
</body>
</html>
